api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: true
      targetPort: {{ targetPortOrDefault 8080 }}
      transport: http
      allowInsecure: false
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: applicationinsights-connection-string
        value: '{{ .Env.APPINSIGHTS_APPINSIGHTSCONNECTIONSTRING }}'
      - name: connectionstrings--aifoundry
        value: '{{ .Env.AIFOUNDRY_CONNECTIONSTRING }}'
      - name: connectionstrings--aifoundryproject
        value: '{{ securedParameter "aifoundryproject" }}'
      - name: connectionstrings--customerinformationagentid
        value: '{{ securedParameter "customerinformationagentid" }}'
  template:
    containers:
      - image: {{ .Image }}
        name: customerinformationservice
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: AI_ChatDeploymentName
            value: gpt-5-mini
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: HTTP_PORTS
            value: '{{ targetPortOrDefault 0 }}'
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: APPLICATIONINSIGHTS_CONNECTION_STRING
            secretRef: applicationinsights-connection-string
          - name: ConnectionStrings__aifoundry
            secretRef: connectionstrings--aifoundry
          - name: ConnectionStrings__aifoundryproject
            secretRef: connectionstrings--aifoundryproject
          - name: ConnectionStrings__customerinformationagentid
            secretRef: connectionstrings--customerinformationagentid
    scale:
      minReplicas: 1
tags:
  azd-service-name: customerinformationservice
  aspire-resource-name: customerinformationservice
